version: '3'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - POSTGRES=${POSTGRES}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - BCRYPT_PASSWORD=${BCRYPT_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - POSTGRES_DB=${POSTGRES_DB}
  client:
    build: ./client
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=REACT_APP_API_URL
      - REACT_APP_IS_DEMO=${REACT_APP_IS_DEMO}
      - REACT_APP_URL=${REACT_APP_URL}
